### ISSUE TITLE
Findings identified by their short names

### ISSUE THREAD

**Issue by pawelbanas** [joaocarloscardoso/AITAM#111]
Findings are identified by sequential numbers now, this is more readable than a previous way but can be still enhanced by:
- a meaningful short name to be added to each finding
- the sequential label can stay as second way of identification
- recommendation - identified by a sequential number, will be now related to one or more short named findings

Thus, logical connections between the findings and recommendations can be easier assessed by reader.

**Comment by joaocarloscardoso** [comment]
The audit xml file muste contemplate now an attribute "name" for the finding element:
`<Case nr="" nm="" eff="" act="" doc="" Include="" number="" name="">`

The must be retrocompatible with previous versions

**Comment by joaocarloscardoso** [comment]
Further implications:
- [ ] findings dashboard
- [ ] Recommendations assignment
- [ ] audit tree map

**Comment by joaocarloscardoso** [comment]
Affected objetcs:
`/partials/`:
- [ ] `auditfindingsheader.ejs`
- [ ] `auditfindingsrow.ejs`

`/partials/audit_matrices/:`
- [ ] `findings.ejs`
- [ ] `findingdata.ejs`
