### ISSUE TITLE
Recommendations table - 'Delete' to the last column

### ISSUE THREAD

**Issue by pawelbanas** [joaocarloscardoso/AITAM#112]
Move the 'delete' option from the first column of Recommendations' table to the last one. It will reduce possibility of unaware removals.

**Comment by joaocarloscardoso** [comment]
Moved the operation, as requested, to the lasta column of dashboard.
Affected objects:
- `auditrecheader.ejs`
- `auditrecrow.ejs`

**Comment by joaocarloscardoso** [comment]
This move was also applied to Findings dashboard
