### ISSUE TITLE
Analytics of Domains selected in Plan

### ISSUE THREAD

**Issue by pawelbanas** [joaocarloscardoso/AITAM#146]
A ranking of 'most risky' domains/areas, could be added

**Comment by joaocarloscardoso** [comment]
Good idea, but we have to decide on:

- an algorithm to rank the elements (domains and areas)
- Include in tsatistics and risk heat matrix

**Comment by pawelbanas** [comment]
Bravo for this progress list! Sorry for some repeated tasks. I should look
first into the github version, not only at the rolled out one...

Maybe to start trying the ranking list from:
- List Areas: weight + count of all issues
- List Domains:  weight + count of all areas
A threshold needed to show only top of the list sorted from largest to
smallest.
I thought more about enriching the Domains characterization page. The Heat
matrix seems to be fine as it is, for me.
Of course, no rush with this task at all. I just wanted to take it down to
remember.

We see each other (online) then on Monday? Maciej  was a bit worried about
the SAACB team, as Ismat is on a pilgrimage trip. But we will see. My
suggestion was to start from the same Budżet & Finance Dep. experts - we
will see. Maybe we can start as usual on 7 Lisbon time to see each other
and exchange ideas+news? Can sure be later if you only prefer.

Best from the Amman Airport
Paweł

pt., 1 lip 2022 o 10:39 joaocarloscardoso ***@***.***>
napisał(a):

**Comment by joaocarloscardoso** [comment]
Ok. We can start at usual hour: 7h00, lisbon time

**Comment by joaocarloscardoso** [comment]
On presentation layer:
- Horizontal bars with domain name and risk rank as value
- ejs file: `/views/partials/audit_statistics/DomainRisky.ejs` 
- Available inside domain characterization and audit dashboard (here, with hyperlink to heat risk matrix)

**Comment by joaocarloscardoso** [comment]
Statistics pages affected:
- `/views/partials/audit_statistics.ejs`
