### ISSUE TITLE
Analytics of Domains/Areas selected in Plan

### ISSUE THREAD

**Issue by pawelbanas** [joaocarloscardoso/AITAM#147]
Full names of Domains / Areas would be helpful

**Comment by joaocarloscardoso** [comment]
Areas names are to big for charts. Since the graphs are generated automatically, the tests demonstrate that the graphs, in order  to accommodate the names, are unreadable

**Comment by joaocarloscardoso** [comment]
Possibility of using full names of Domains / Areas in tooltips
